# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "2d6c7d2f1c293941a5053e43fd1f632b"
name = "2405-2"
handle = "2405-2"
application_url = "https://controls-cap-neighbor-between.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "codeinspire2.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://controls-cap-neighbor-between.trycloudflare.com/auth/callback",
  "https://controls-cap-neighbor-between.trycloudflare.com/auth/shopify/callback",
  "https://controls-cap-neighbor-between.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

  [webhooks.privacy_compliance]
  customer_deletion_url = "https://solo-katie-acute-wr.trycloudflare.com/webhooks"
  customer_data_request_url = "https://solo-katie-acute-wr.trycloudflare.com/webhooks"
  shop_deletion_url = "https://solo-katie-acute-wr.trycloudflare.com/webhooks"

[pos]
embedded = true
